[package]
name = "godotexit"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ctrlc = "3.4.2"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }

